name: Go

on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build windows 64
      run:  env GOOS=windows GOARCH=amd64 go build -v ./...
      
    - name: Build linux 64
      run:  env GOOS=linux GOARCH=amd64 go build -v ./...
      
    - name: Build rpi arm6
      run:  env GOOS=linux GOARCH=arm GOARM=6 go build -v ./...
      
    - name: Build rpi arm7
      run:  env GOOS=linux GOARCH=arm GOARM=7 go build -v ./...
