name: Go

on:
  push:
    tags:
    - '*'
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build all
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go env GOPATH
        echo "ls"
        ls
        echo "ls $(go env GOPATH)"
        ls $(go env GOPATH)
        echo "ls $(go env GOPATH)/bin"
        ls $(go env GOPATH)/bin
        go get -v
        gox -arch="amd64 386 armv5 armv6 armv7" -os="windows linux" -output="build/{{.Dir}}_{{.OS}}_{{.Arch}}"

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true